### PR TITLE
Fix duplicate listeners and listeners on pause

### PR DESCRIPTION
**Pull request by gmaclennan**
This fixes two things:

1. In some circumstances, listeners were being added twice to every feed. This PR avoids duplicate listeners.
2. I was trying to get to the bottom of sync slowdown, especially with mobile. I think one of the causes is that even though the index is paused, all the event listeners on the feed `append` events are firing for every record being added. So during a fresh sync that is `number of records x number of feeds x number of indexes`. For sinangoe data with 10 feeds, that means the `_run()` method would be called 55,000 x 10 x 6 = 3,300,000 times, which I think was one of the causes of slowdown. This PR removes all listeners on pause, and adds them back on resume.

### CODE REVIEW

**Comment by hackergrrl** [comment]
Did you observe sync speeding up with this change?

**Comment by hackergrrl** [comment]
Did you observe sync speeding up with this change?

**Comment by gmaclennan** [comment]
I made this change and also throttled updates on the front-end at the same time. Sync was faster, and CPU went from 400% during sync to 200%, although that could have been the front-end changes. I didn't test them separately. I can confirm that duplicate event listeners were being added. But I haven't measured sync speedups. I made an assumption that 1 million+ function calls during sync would have a performance impact, but it might be negligible. I can do more testing. Perhaps maybe this should be two PRs? One for the removal of dup event listeners, and the other for removing listeners during pause?

**Comment by gmaclennan** [comment]
An update on this, I tested sync with a dataset of 55K records with and without this change. The difference in speed was minimal, 245 seconds vs 258 seconds.

**Pull request merged**
